using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using N.EntityFrameworkCore.Extensions.Common;
using N.EntityFrameworkCore.Extensions.Util;

namespace N.EntityFrameworkCore.Extensions;

internal sealed partial class BulkOperation<T>
{
    internal async Task<BulkInsertResult<T>> BulkInsertStagingDataAsync(IEnumerable<T> entities, bool keepIdentity = true, bool useInternalId = false, CancellationToken cancellationToken = default)
    {
        var columnsToInsert = GetColumnNames(keepIdentity).ToList();
        string internalIdColumn = useInternalId ? Common.Constants.InternalId_ColumnName : null;
        stagingColumnNames = columnsToInsert.ToHashSet(StringComparer.OrdinalIgnoreCase);
        if (internalIdColumn != null)
            stagingColumnNames.Add(internalIdColumn);
        await Context.Database.CloneTableAsync(SchemaQualifiedTableNames, StagingTableName, TableMapping.GetQualifiedColumnNames(columnsToInsert), internalIdColumn, cancellationToken, isTemporary: !Options.UsePermanentTable);
        StagingTableCreated = true;
        if (keepIdentity)
            await EnsureStagingIndexAsync(PrimaryKeyColumnNames, cancellationToken);
        return await DbContextExtensionsAsync.BulkInsertAsync(entities, Options, TableMapping, Connection, Transaction, StagingTableName, columnsToInsert, useInternalId, cancellationToken);
    }

    internal async Task<BulkMergeResult<T>> ExecuteMergeAsync(Dictionary<long, T> entityMap, Expression<Func<T, T, bool>> mergeOnCondition,
        bool autoMapOutput, bool keepIdentity, bool insertIfNotExists, bool update = false, bool delete = false, bool preallocatedIds = false, CancellationToken cancellationToken = default)
    {
        return await ExecuteMergeMySqlAsync(entityMap, mergeOnCondition, autoMapOutput, keepIdentity, insertIfNotExists, update, delete, preallocatedIds, cancellationToken);
    }
    internal async Task<int> ExecuteUpdateAsync(IEnumerable<T> entities, Expression<Func<T, T, bool>> updateOnCondition, CancellationToken cancellationToken = default)
    {
        return await ExecuteUpdateMySqlAsync(updateOnCondition, cancellationToken);
    }
    private async Task<BulkMergeResult<T>> ExecuteMergeMySqlAsync(Dictionary<long, T> entityMap, Expression<Func<T, T, bool>> mergeOnCondition,
        bool autoMapOutput, bool keepIdentity, bool insertIfNotExists, bool update, bool delete, bool preallocatedIds = false, CancellationToken cancellationToken = default)
    {
        Dictionary<IEntityType, int> rowsInserted = [];
        Dictionary<IEntityType, int> rowsUpdated = [];
        Dictionary<IEntityType, int> rowsDeleted = [];
        List<BulkMergeOutputRow<T>> outputRows = [];

        if (update || delete || insertIfNotExists || autoMapOutput)
            await EnsureStagingIndexAsync(GetStagingJoinColumns(mergeOnCondition), cancellationToken);

        foreach (var entityType in TableMapping.EntityTypes)
        {
            var targetTableName = Context.DelimitIdentifier(entityType.GetTableName(), entityType.GetSchema() ?? Context.Database.GetDefaultSchema());
            var columnsToInsert = GetColumnNames(entityType, keepIdentity).ToList();
            var columnsToUpdate = update ? GetColumnNames(entityType).ToList() : [];
            var autoGeneratedColumns = autoMapOutput ? TableMapping.GetAutoGeneratedColumns(entityType).ToList() : [];
            var allProperties = autoMapOutput
                ? TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAdd).Concat(TableMapping.GetEntityProperties(entityType, ValueGenerated.OnAddOrUpdate)).ToList()
                : [];

            string matchJoinCondition = CommonUtil<T>.GetJoinConditionSql(Context, mergeOnCondition, PrimaryKeyColumnNames, "s", "t");
            string pkJoinCondition = CommonUtil<T>.GetJoinConditionSql(Context, null, PrimaryKeyColumnNames, "s", "t");
            string joinCondition = insertIfNotExists ? matchJoinCondition : "1=2";

            HashSet<int> matchedIds = autoMapOutput && update
                ? await GetMatchedInternalIdsAsync(targetTableName, matchJoinCondition, cancellationToken)
                : [];

            rowsUpdated[entityType] = 0;
            if (columnsToUpdate.Count > 0)
            {
                if (!ReturnsMatchedRowsForUpdates())
                {
                    string matchCountSql = $"SELECT COUNT(*) FROM {StagingTableName} AS s INNER JOIN {targetTableName} AS t ON {joinCondition}";
                    rowsUpdated[entityType] = Convert.ToInt32(await Context.Database.ExecuteScalarAsync(matchCountSql, null, Options.CommandTimeout, cancellationToken));
                }

                string updateSetExpression = string.Join(",", columnsToUpdate.Select(c => $"t.{Context.DelimitIdentifier(c)}=s.{Context.DelimitIdentifier(c)}"));
                string updateSql = $"UPDATE {StagingTableName} AS s INNER JOIN {targetTableName} AS t ON {joinCondition} SET {updateSetExpression}";
                int updateRows = await Context.Database.ExecuteSqlAsync(updateSql, Options.CommandTimeout, cancellationToken);
                if (ReturnsMatchedRowsForUpdates())
                    rowsUpdated[entityType] = updateRows;
            }

            rowsDeleted[entityType] = 0;
            if (TableMapping.EntityType == entityType && delete)
            {
                string deleteJoinCondition = mergeOnCondition != null ? matchJoinCondition : pkJoinCondition;
                string deleteSql = $"DELETE t FROM {targetTableName} AS t WHERE NOT EXISTS (SELECT 1 FROM {StagingTableName} AS s WHERE {deleteJoinCondition})";
                rowsDeleted[entityType] = await Context.Database.ExecuteSqlAsync(deleteSql, Options.CommandTimeout, cancellationToken);
                for (int i = 0; i < rowsDeleted[entityType]; i++)
                    outputRows.Add(new BulkMergeOutputRow<T>(SqlMergeAction.Delete));
            }

            string insertColumnsSql = string.Join(",", columnsToInsert.Select(Context.DelimitIdentifier));
            string sourceColumnsSql = string.Join(",", columnsToInsert.Select(c => Context.DelimitMemberAccess("s", c)));
            bool useLastInsertId = autoMapOutput && !keepIdentity && mergeOnCondition == null && autoGeneratedColumns.Any();
            string insertOrderBy = useLastInsertId ? $" ORDER BY s.{Context.DelimitIdentifier(Constants.InternalId_ColumnName)}" : "";
            string insertSql = $"INSERT INTO {targetTableName} ({insertColumnsSql}) SELECT {sourceColumnsSql} FROM {StagingTableName} AS s WHERE NOT EXISTS (SELECT 1 FROM {targetTableName} AS t WHERE {joinCondition}){insertOrderBy}";
            rowsInserted[entityType] = await Context.Database.ExecuteSqlAsync(insertSql, Options.CommandTimeout, cancellationToken);
            if (keepIdentity && rowsInserted[entityType] > 0)
                await SyncMySqlAutoIncrementAsync(entityType, cancellationToken);

            if (autoMapOutput)
            {
                if (useLastInsertId && rowsInserted[entityType] > 0)
                {
                    var lastInsertResult = await Context.BulkQueryAsync("SELECT LAST_INSERT_ID()", Connection, Transaction, Options, cancellationToken);
                    long firstAutoId = Convert.ToInt64(lastInsertResult.Results.First()[0]);
                    var insertedEntities = entityMap
                        .Where(kvp => !matchedIds.Contains((int)kvp.Key))
                        .OrderBy(kvp => kvp.Key)
                        .ToList();
                    for (int k = 0; k < insertedEntities.Count; k++)
                    {
                        var entity = insertedEntities[k].Value;
                        long generatedId = firstAutoId + k;
                        var generatedPkProperty = GetGeneratedPrimaryKeyProperty();
                        if (generatedPkProperty != null)
                        {
                            object pkValue = Convert.ChangeType(generatedId, generatedPkProperty.ClrType);
                            Context.SetStoreGeneratedValues(entity, [generatedPkProperty], [pkValue]);
                        }
                        outputRows.Add(new BulkMergeOutputRow<T>(SqlMergeAction.Insert));
                    }
                }
                else
                {
                    string outputColumnsSql = autoGeneratedColumns.Any()
                        ? "," + string.Join(",", autoGeneratedColumns.Select(c => Context.DelimitMemberAccess("t", c)))
                        : string.Empty;
                    string outputQuery = $"SELECT {Context.DelimitMemberAccess("s", Constants.InternalId_ColumnName)}{outputColumnsSql} FROM {StagingTableName} AS s JOIN {targetTableName} AS t ON {matchJoinCondition}";
                    var bulkQueryResult = await Context.BulkQueryAsync(outputQuery, Connection, Transaction, Options, cancellationToken);
                    var autoGeneratedColumnList = autoGeneratedColumns.ToList();
                    foreach (var result in bulkQueryResult.Results)
                    {
                        int entityId = Convert.ToInt32(result[0]);
                        string action = matchedIds.Contains(entityId) ? SqlMergeAction.Update : SqlMergeAction.Insert;
                        outputRows.Add(new BulkMergeOutputRow<T>(action));

                        if (entityMap.TryGetValue(entityId, out var entity) && allProperties.Count > 0)
                        {
                            object[] entityValues = allProperties.Select(p => result[1 + autoGeneratedColumnList.IndexOf(p.GetColumnName())]).ToArray();
                            Context.SetStoreGeneratedValues(entity, allProperties, entityValues);
                        }
                    }
                }
            }
        }

        return new BulkMergeResult<T>
        {
            Output = outputRows,
            RowsAffected = GetLogicalRowCount(rowsInserted) + GetLogicalRowCount(rowsUpdated) + GetLogicalRowCount(rowsDeleted),
            RowsDeleted = GetLogicalRowCount(rowsDeleted),
            RowsInserted = GetLogicalRowCount(rowsInserted),
            RowsUpdated = GetLogicalRowCount(rowsUpdated)
        };
    }
    private async Task<int> ExecuteUpdateMySqlAsync(Expression<Func<T, T, bool>> updateOnCondition, CancellationToken cancellationToken)
    {
        int rowsUpdated = 0;
        await EnsureStagingIndexAsync(GetStagingJoinColumns(updateOnCondition), cancellationToken);
        foreach (var entityType in TableMapping.EntityTypes)
        {
            IEnumerable<string> columnsToUpdate = GetColumnNames(entityType);
            string updateSetExpression = string.Join(",", columnsToUpdate.Select(c => $"t.{Context.DelimitIdentifier(c)}=s.{Context.DelimitIdentifier(c)}"));
            string targetTableName = Context.DelimitIdentifier(entityType.GetTableName(), entityType.GetSchema() ?? Context.Database.GetDefaultSchema());
            string updateSql = $"UPDATE {StagingTableName} AS s INNER JOIN {targetTableName} AS t ON {CommonUtil<T>.GetJoinConditionSql(Context, updateOnCondition, PrimaryKeyColumnNames, "s", "t")} SET {updateSetExpression}";
            rowsUpdated = Math.Max(rowsUpdated, await Context.Database.ExecuteSqlAsync(updateSql, Options.CommandTimeout, cancellationToken));
        }
        return rowsUpdated;
    }
    private async Task EnsureStagingIndexAsync(IEnumerable<string> columns, CancellationToken cancellationToken)
    {
        // ALTER TABLE causes an implicit commit in MySQL, which would break a user-provided transaction.
        if (!Context.Database.IsMySql() || !DbTransactionContext.OwnsTransaction)
            return;

        var indexColumns = columns?
            .Where(c => stagingColumnNames.Contains(c))
            .Where(CanIndexStagingColumn)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList() ?? [];

        if (indexColumns.Count == 0)
            return;

        string indexKey = string.Join("|", indexColumns);
        if (!stagingIndexes.Add(indexKey))
            return;

        string indexName = Context.DelimitIdentifier($"idx_staging_{stagingIndexes.Count}");
        string delimitedColumns = string.Join(",", indexColumns.Select(c => Context.DelimitIdentifier(c)));
        await Context.Database.ExecuteSqlAsync($"ALTER TABLE {StagingTableName} ADD INDEX {indexName} ({delimitedColumns})", Options.CommandTimeout, cancellationToken);
    }
    internal async Task PreallocateIdentityValuesAsync(IEnumerable<T> entities, CancellationToken cancellationToken)
    {
        // No-op for MySQL
        await Task.CompletedTask;
    }
    private async Task<HashSet<int>> GetMatchedInternalIdsAsync(string targetTableName, string joinCondition, CancellationToken cancellationToken)
    {
        var results = await Context.BulkQueryAsync(
            $"SELECT {Context.DelimitMemberAccess("s", Constants.InternalId_ColumnName)} FROM {StagingTableName} AS s JOIN {targetTableName} AS t ON {joinCondition}",
            Connection, Transaction, Options, cancellationToken);
        return results.Results.Select(r => Convert.ToInt32(r[0])).ToHashSet();
    }
    private async Task SyncMySqlAutoIncrementAsync(IEntityType entityType, CancellationToken cancellationToken)
    {
        var tableName = Context.DelimitIdentifier(entityType.GetTableName(), entityType.GetSchema() ?? Context.Database.GetDefaultSchema());
        await Context.Database.ExecuteSqlAsync($"ALTER TABLE {tableName} AUTO_INCREMENT = 1", Options.CommandTimeout, cancellationToken);
    }
}
